### ISSUE TITLE
explain script

### ISSUE THREAD

**Issue by Ayysir** [T3rrabyte/StreamMarker#1]
I was browsing github looking for a stream marker script for macro pad to use and stumbled onto this. How does this script work? which python version is this for?

```ModuleNotFoundError: No module named 'requests'``` when i try running this

**Comment by T3rrabyte** [comment]
This is a stream marker for Twitch. If requests cannot be found, you must install it using pip or some other method.

`pip install requests` or `pip3 install requests`, depending on your Python version(s). You should be able to run the executable just fine without installing any of the libraries, though.

I apologize for taking so long to get back to you on the issue; I didn't really plan on ever checking this repository again since it's a very quick project.

**Comment by T3rrabyte** [comment]
I updated the application description to mirror this. I didn't realize it was never mentioned anywhere outside of the code before that.

Thank you for your input.

**Comment by Ayysir** [comment]
I was looking for a script I could run via autohotkey through python script

**Comment by T3rrabyte** [comment]
I don't really know what you mean by that, but it seems like you aren't finding what you need here. If this application isn't made for what you want, try looking for a different program.

**Comment by Ayysir** [comment]
> I don't really know what you mean by that, but it seems like you aren't finding what you need here. If this application isn't made for what you want, try looking for a different program.

meaning i am trying to initiate the script using a macropad
